name: Build, Lint & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint check
        run: |
          pip install flake8
          flake8 app/api/routes.py --max-line-length=100

        env:
          PYTHONPATH: .
        
      - name: Run tests
        run: |
          pip install pytest
          pytest